dist: xenial
language: python
git:
  depth: false
branches:
  except:
    - upstream
addons:
  apt:
    packages:
      - gnupg
      - zip
services:
  - docker
before_install:
  # setup git
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'contact@travis-ci.com'
  - git remote remove origin
  - git remote add origin git@github.com:BananaWanted/beancount.git
  # setup ssh
  - openssl aes-256-cbc -K $encrypted_3dd051e32a99_key -iv $encrypted_3dd051e32a99_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - rm -f github_deploy_key
  # setup mercurial
  - printf '[extensions]\nhgext.bookmarks =\nhggit =\n' > ~/.hgrc
  - sudo pip2 install -U 'hg+https://bitbucket.org/durin42/hg-git' brotli ipaddress pyOpenSSL ndg-httpsclient pyasn1
  - hg version -v
  # setup docker
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

install:
  # sync upstream
  - hg clone https://bitbucket.org/blais/beancount ../upstream
  - cd ../upstream
  - hg bookmark upstream
  - hg push ../beancount
  - cd ../beancount
  - rm -rf .git/refs/tags/*
  - git reset --hard
  - git checkout upstream
  - git push origin upstream

before_script:
  # merge upstream into current branch
  - git reset --hard
  - git checkout $TRAVIS_BRANCH
  - git merge -m 'sync upstream from https://bitbucket.org/blais/beancount' upstream
  # checkout & merge pull request branch if applicable
  - if [[ -n "$TRAVIS_PULL_REQUEST_BRANCH" ]]; then git checkout -b $TRAVIS_PULL_REQUEST_BRANCH && git merge origin/$TRAVIS_PULL_REQUEST_BRANCH; fi
  # install the package
  - pip install -r requirements.txt
  - pip install . pylint pyflakes tox

script:
  # run test, ignore any errors
  - make check || true
  # build docker image
  - docker build
    -t $DOCKER_HUB_USERNAME/beancount
    -t $DOCKER_HUB_USERNAME/beancount:${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    --rm .

after_success:
  # push to DockerHub
  - docker push $DOCKER_HUB_USERNAME/beancount:${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  # for latest tag, only push when: non-PR job && master branch && no merge happens on master in the job
  - if [[ -z "$TRAVIS_PULL_REQUEST_BRANCH" -a "$TRAVIS_BRANCH" = "master" -a "$(git rev-parse --verify master)" = "$(git rev-parse --verify origin/master)" ]]; then docker push $DOCKER_HUB_USERNAME/beancount; fi
  # push to GitHub, checkout to targeted branch beforhand in case this is a pull request job
  - git checkout $TRAVIS_BRANCH
  - git push origin $TRAVIS_BRANCH
